//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MenuStolovayaDBEntities : DbContext
    {
        public MenuStolovayaDBEntities()
            : base("name=MenuStolovayaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Блюда> Блюда { get; set; }
        public DbSet<Виды_блюд> Виды_блюд { get; set; }
        public DbSet<Калькуляционные_карточки> Калькуляционные_карточки { get; set; }
        public DbSet<Категории_продуктов> Категории_продуктов { get; set; }
        public DbSet<Меню_на_день> Меню_на_день { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<Продукты> Продукты { get; set; }
        public DbSet<Рецептуры> Рецептуры { get; set; }
        public DbSet<Роли> Роли { get; set; }
        public DbSet<Строки_калькуляции> Строки_калькуляции { get; set; }
        public DbSet<Строки_меню> Строки_меню { get; set; }
        public DbSet<Технологические_карты> Технологические_карты { get; set; }
        public DbSet<vw_Анализ_себестоимости> vw_Анализ_себестоимости { get; set; }
        public DbSet<vw_Калькуляционные_карточки_полные> vw_Калькуляционные_карточки_полные { get; set; }
        public DbSet<vw_Меню_с_ценами> vw_Меню_с_ценами { get; set; }
        public DbSet<vw_Рентабельность_блюд> vw_Рентабельность_блюд { get; set; }
        public DbSet<vw_Технологические_карты_полные> vw_Технологические_карты_полные { get; set; }
    }
}
