
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Анализ_себестоимости
{

    public string Блюдо { get; set; }

    public decimal Выход_порции_г { get; set; }

    public Nullable<decimal> Себестоимость_общая { get; set; }

    public Nullable<decimal> Себестоимость_за_кг { get; set; }

    public Nullable<int> Количество_ингредиентов { get; set; }

    public Nullable<decimal> Макс_стоимость_ингредиента { get; set; }

    public Nullable<decimal> Мин_стоимость_ингредиента { get; set; }

    public Nullable<decimal> Сред_стоимость_ингредиента { get; set; }

}

}
