
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Меню_с_ценами
{

    public Nullable<long> C_п_п { get; set; }

    public System.DateTime Дата { get; set; }

    public string Блюдо { get; set; }

    public string Вид_блюда { get; set; }

    public Nullable<decimal> Цена { get; set; }

    public Nullable<decimal> Фудкост_процент { get; set; }

    public Nullable<int> Количество_порций { get; set; }

    public Nullable<decimal> Выход_г { get; set; }

    public Nullable<decimal> Общая_выручка { get; set; }

    public Nullable<decimal> Калорийность_на_порцию { get; set; }

    public string Статус_меню { get; set; }

}

}
