//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Калькуляционные_карточки_полные
    {
        public string Номер { get; set; }
        public string Блюдо { get; set; }
        public decimal Выход_порции_г { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
        public Nullable<decimal> Цена_реализации { get; set; }
        public Nullable<decimal> Фудкост_процент { get; set; }
        public Nullable<decimal> Процент_наценки { get; set; }
        public string Маржинальность { get; set; }
        public string Статус { get; set; }
        public string Кто_утвердил { get; set; }
        public string Тех_карта { get; set; }
    }
}
