
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Рентабельность_блюд
{

    public string Блюдо { get; set; }

    public decimal Выход_порции_г { get; set; }

    public string Кальк_карта { get; set; }

    public Nullable<decimal> Себестоимость { get; set; }

    public Nullable<decimal> Цена_реализации { get; set; }

    public Nullable<decimal> Фудкост_процент { get; set; }

    public Nullable<decimal> Процент_наценки { get; set; }

    public Nullable<decimal> Прибыль_на_порцию { get; set; }

    public Nullable<decimal> Маржа_процент { get; set; }

    public string Оценка_рентабельности { get; set; }

}

}
