
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Текущие_остатки
{

    public int Склад_id { get; set; }

    public string Склад { get; set; }

    public string Артикул { get; set; }

    public string Продукт { get; set; }

    public string Категория { get; set; }

    public string Единица_измерения { get; set; }

    public decimal Количество { get; set; }

    public decimal Цена_за_единицу { get; set; }

    public decimal Сумма { get; set; }

    public Nullable<decimal> Цена_последняя_закупка { get; set; }

    public Nullable<System.DateTime> Дата_обновления { get; set; }

}

}
