
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Требования_накладные
{

    public int id { get; set; }

    public string Номер { get; set; }

    public System.DateTime Дата_документа { get; set; }

    public System.DateTime Дата_меню { get; set; }

    public string Технолог { get; set; }

    public string Статус_требования { get; set; }

    public string Статус_документа { get; set; }

    public string Комментарий { get; set; }

    public string Кладовщик { get; set; }

    public Nullable<System.DateTime> Дата_обработки { get; set; }

    public decimal Общее_количество { get; set; }

    public decimal Общая_сумма { get; set; }

}

}
