
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class vw_Требования_детали
{

    public string Номер_требования { get; set; }

    public string Артикул { get; set; }

    public string Продукт { get; set; }

    public string Единица_измерения { get; set; }

    public decimal Количество { get; set; }

    public decimal Цена { get; set; }

    public Nullable<decimal> Сумма { get; set; }

    public decimal Остаток_на_складе { get; set; }

}

}
