//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Технологические_карты_полные
    {
        public string Номер { get; set; }
        public string Блюдо { get; set; }
        public decimal Выход_порции_г { get; set; }
        public string Технология_приготовления { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public string Статус { get; set; }
        public string Кто_утвердил { get; set; }
        public Nullable<System.DateTime> Дата_утверждения { get; set; }
        public Nullable<int> Количество_ингредиентов { get; set; }
    }
}
