//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Блюда
    {
        public Блюда()
        {
            this.Строки_меню = new HashSet<Строки_меню>();
            this.Технологические_карты = new HashSet<Технологические_карты>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string Полное_наименование { get; set; }
        public Nullable<int> Вид_блюда_id { get; set; }
        public Nullable<decimal> Выход_стандартный { get; set; }
        public Nullable<int> Время_приготовления { get; set; }
        public Nullable<decimal> Калорийность_расчетная { get; set; }
        public Nullable<bool> Активно { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> Кто_создал_id { get; set; }
    
        public virtual Виды_блюд Виды_блюд { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual ICollection<Строки_меню> Строки_меню { get; set; }
        public virtual ICollection<Технологические_карты> Технологические_карты { get; set; }
    }
}
