//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виды_блюд
    {
        public Виды_блюд()
        {
            this.Блюда = new HashSet<Блюда>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
    
        public virtual ICollection<Блюда> Блюда { get; set; }
    }
}
