
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Документы
{

    public Документы()
    {

        this.Строки_документов = new HashSet<Строки_документов>();

        this.Требования_накладные = new HashSet<Требования_накладные>();

    }


    public int id { get; set; }

    public string Номер { get; set; }

    public string Тип_документа { get; set; }

    public Nullable<System.DateTime> Дата_создания { get; set; }

    public System.DateTime Дата_документа { get; set; }

    public Nullable<int> Склад_отправитель_id { get; set; }

    public Nullable<int> Склад_получатель_id { get; set; }

    public string Основание { get; set; }

    public string Статус { get; set; }

    public int Кто_создал_id { get; set; }

    public Nullable<int> Кто_провел_id { get; set; }

    public Nullable<System.DateTime> Дата_проведения { get; set; }

    public string Комментарий { get; set; }



    public virtual Пользователи Пользователи { get; set; }

    public virtual Пользователи Пользователи1 { get; set; }

    public virtual Склады Склады { get; set; }

    public virtual Склады Склады1 { get; set; }

    public virtual ICollection<Строки_документов> Строки_документов { get; set; }

    public virtual ICollection<Требования_накладные> Требования_накладные { get; set; }

}

}
