//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Калькуляционные_карточки
    {
        public Калькуляционные_карточки()
        {
            this.Строки_калькуляции = new HashSet<Строки_калькуляции>();
        }
    
        public int id { get; set; }
        public string Номер { get; set; }
        public int Технологическая_карта_id { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
        public Nullable<decimal> Процент_наценки { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
        public Nullable<decimal> Цена_реализации { get; set; }
        public Nullable<decimal> Food_Cost { get; set; }
        public string Статус { get; set; }
        public Nullable<int> Кто_утвердил_id { get; set; }
        public Nullable<System.DateTime> Дата_утверждения { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Технологические_карты Технологические_карты { get; set; }
        public virtual ICollection<Строки_калькуляции> Строки_калькуляции { get; set; }
    }
}
