//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Меню_на_день
    {
        public Меню_на_день()
        {
            this.Строки_меню = new HashSet<Строки_меню>();
        }
    
        public int id { get; set; }
        public System.DateTime Дата { get; set; }
        public int Ответственный_id { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
        public Nullable<decimal> Калорийность_общая { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ICollection<Строки_меню> Строки_меню { get; set; }
    }
}
