
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Остатки_продуктов
{

    public int id { get; set; }

    public int Склад_id { get; set; }

    public int Продукт_id { get; set; }

    public decimal Количество { get; set; }

    public decimal Цена_за_единицу { get; set; }

    public Nullable<decimal> Сумма { get; set; }

    public Nullable<System.DateTime> Дата_обновления { get; set; }



    public virtual Продукты Продукты { get; set; }

    public virtual Склады Склады { get; set; }

}

}
