//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public Пользователи()
        {
            this.Блюда = new HashSet<Блюда>();
            this.Калькуляционные_карточки = new HashSet<Калькуляционные_карточки>();
            this.Меню_на_день = new HashSet<Меню_на_день>();
            this.Продукты = new HashSet<Продукты>();
            this.Технологические_карты = new HashSet<Технологические_карты>();
        }
    
        public int id { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Роль_id { get; set; }
        public Nullable<bool> Блокировка { get; set; }
        public Nullable<System.DateTime> Дата_регистрации { get; set; }
    
        public virtual ICollection<Блюда> Блюда { get; set; }
        public virtual ICollection<Калькуляционные_карточки> Калькуляционные_карточки { get; set; }
        public virtual ICollection<Меню_на_день> Меню_на_день { get; set; }
        public virtual Роли Роли { get; set; }
        public virtual ICollection<Продукты> Продукты { get; set; }
        public virtual ICollection<Технологические_карты> Технологические_карты { get; set; }
    }
}
