
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Продукты
{

    public Продукты()
    {

        this.Рецептуры = new HashSet<Рецептуры>();

        this.Строки_калькуляции = new HashSet<Строки_калькуляции>();

        this.Остатки_продуктов = new HashSet<Остатки_продуктов>();

        this.Строки_документов = new HashSet<Строки_документов>();

    }


    public int id { get; set; }

    public string Артикул { get; set; }

    public string Наименование { get; set; }

    public Nullable<int> Категория_id { get; set; }

    public string Единица_измерения { get; set; }

    public Nullable<decimal> Потери_холодной_обработки { get; set; }

    public Nullable<decimal> Потери_горячей_обработки { get; set; }

    public Nullable<decimal> Белки { get; set; }

    public Nullable<decimal> Жиры { get; set; }

    public Nullable<decimal> Углеводы { get; set; }

    public Nullable<decimal> Калорийность { get; set; }

    public Nullable<decimal> Цена { get; set; }

    public Nullable<bool> Утверждена_цена { get; set; }

    public Nullable<int> Кто_утвердил_цену_id { get; set; }

    public Nullable<System.DateTime> Дата_утверждения_цены { get; set; }

    public Nullable<bool> Активен { get; set; }



    public virtual Категории_продуктов Категории_продуктов { get; set; }

    public virtual Пользователи Пользователи { get; set; }

    public virtual ICollection<Рецептуры> Рецептуры { get; set; }

    public virtual ICollection<Строки_калькуляции> Строки_калькуляции { get; set; }

    public virtual ICollection<Остатки_продуктов> Остатки_продуктов { get; set; }

    public virtual ICollection<Строки_документов> Строки_документов { get; set; }

}

}
