//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рецептуры
    {
        public int id { get; set; }
        public int Технологическая_карта_id { get; set; }
        public int Продукт_id { get; set; }
        public decimal Количество_брутто { get; set; }
        public Nullable<decimal> Количество_нетто { get; set; }
        public Nullable<int> Порядок_закладки { get; set; }
    
        public virtual Продукты Продукты { get; set; }
        public virtual Технологические_карты Технологические_карты { get; set; }
    }
}
