
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Склады
{

    public Склады()
    {

        this.Документы = new HashSet<Документы>();

        this.Документы1 = new HashSet<Документы>();

        this.Остатки_продуктов = new HashSet<Остатки_продуктов>();

    }


    public int id { get; set; }

    public string Наименование { get; set; }

    public string Адрес { get; set; }

    public Nullable<int> Ответственный_id { get; set; }

    public Nullable<bool> Активен { get; set; }



    public virtual ICollection<Документы> Документы { get; set; }

    public virtual ICollection<Документы> Документы1 { get; set; }

    public virtual ICollection<Остатки_продуктов> Остатки_продуктов { get; set; }

    public virtual Пользователи Пользователи { get; set; }

}

}
