//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строки_калькуляции
    {
        public int id { get; set; }
        public int Калькуляционная_карточка_id { get; set; }
        public int Продукт_id { get; set; }
        public decimal Норма_расхода { get; set; }
        public decimal Цена_за_единицу { get; set; }
        public decimal Сумма { get; set; }
    
        public virtual Калькуляционные_карточки Калькуляционные_карточки { get; set; }
        public virtual Продукты Продукты { get; set; }
    }
}
