
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Строки_документов
{

    public int id { get; set; }

    public int Документ_id { get; set; }

    public int Продукт_id { get; set; }

    public decimal Количество { get; set; }

    public decimal Цена { get; set; }

    public Nullable<decimal> Сумма { get; set; }



    public virtual Документы Документы { get; set; }

    public virtual Продукты Продукты { get; set; }

}

}
