//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuStolovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строки_меню
    {
        public int id { get; set; }
        public int Меню_id { get; set; }
        public int Блюдо_id { get; set; }
        public Nullable<int> Количество_порций { get; set; }
        public Nullable<decimal> Выход_на_порцию { get; set; }
        public string Время_подачи { get; set; }
        public Nullable<int> Порядок_подачи { get; set; }
    
        public virtual Блюда Блюда { get; set; }
        public virtual Меню_на_день Меню_на_день { get; set; }
    }
}
