
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Технологические_карты
{

    public Технологические_карты()
    {

        this.Калькуляционные_карточки = new HashSet<Калькуляционные_карточки>();

        this.Рецептуры = new HashSet<Рецептуры>();

    }


    public int id { get; set; }

    public string Номер { get; set; }

    public int Блюдо_id { get; set; }

    public decimal Выход { get; set; }

    public string Технология_приготовления { get; set; }

    public Nullable<System.DateTime> Дата_создания { get; set; }

    public string Статус { get; set; }

    public Nullable<int> Кто_утвердил_id { get; set; }

    public Nullable<System.DateTime> Дата_утверждения { get; set; }



    public virtual Блюда Блюда { get; set; }

    public virtual ICollection<Калькуляционные_карточки> Калькуляционные_карточки { get; set; }

    public virtual Пользователи Пользователи { get; set; }

    public virtual ICollection<Рецептуры> Рецептуры { get; set; }

}

}
