
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MenuStolovaya
{

using System;
    using System.Collections.Generic;
    
public partial class Требования_накладные
{

    public int id { get; set; }

    public string Номер { get; set; }

    public int Документ_id { get; set; }

    public int Меню_id { get; set; }

    public System.DateTime Дата_требования { get; set; }

    public int Технолог_id { get; set; }

    public string Статус_требования { get; set; }

    public Nullable<int> Кладовщик_id { get; set; }

    public string Комментарий_кладовщика { get; set; }

    public Nullable<System.DateTime> Дата_обработки { get; set; }



    public virtual Документы Документы { get; set; }

    public virtual Меню_на_день Меню_на_день { get; set; }

    public virtual Пользователи Пользователи { get; set; }

    public virtual Пользователи Пользователи1 { get; set; }

}

}
